name: Integration Test

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Geth and bus-mapping test
      uses: actions/checkout@v2
    - run: sh web3-utils/script/geth.sh
